title: warmycat.com
description: WarmyCat 的 LINE Rangers 文章與工具整理
lang: zh-TW
timezone: Asia/Taipei

url: "https://mti0224.github.io"
baseurl: "/blog"

theme: minima

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-paginate

# 分頁設定
paginate: 10
paginate_path: "page:num/" # 這裡使用相對路徑，避免與 /blog 衝突

markdown: kramdown
kramdown:
  input: GFM

permalink: /:year/:month/:day/:title/

exclude:
  - node_modules
  - vendor
  - Gemfile
  - Gemfile.lock
  - README.md
  - .DS_Store
  
defaults:
  - scope:
      path: ""
    values:
      layout: post
  - scope:
      path: ""
    values:
      layout: page
