title: warmycat.com
description: WarmyCat 的 LINE Rangers 文章與工具整理
lang: zh-TW
timezone: Asia/Taipei

# 網址設定 
url: "https://mti0224.github.io"
baseurl: "/blog"

theme: minima

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - [cite_start]jekyll-paginate  # 啟用分頁外掛 

# 分頁核心設定
paginate: 10
paginate_path: "/page:num/" # 加上斜線確保路徑正確

markdown: kramdown
kramdown:
  input: GFM

permalink: /:year/:month/:day/:title/

exclude:
  - node_modules
  - vendor
  - Gemfile
  - Gemfile.lock
  - README.md
  - .DS_Store
  
defaults:
  - scope:
      path: ""
    values:
      layout: post
  - scope:
      path: ""
    values:
      layout: page
